### ISSUE TITLE
is `ragg` open source or not?

### ISSUE THREAD

**Issue by mbutterick** [dyoo/ragg#12]
There is no license, so by default, it is proprietary.

**Comment by dyoo** [comment]
Hi Matthew,

What would be the most convenient OSS license for you?  I was thinking
Apache here, but if you have a preference, please let me know.

On Tue, Mar 15, 2016 at 2:21 PM, Matthew Butterick <notifications@github.com

**Comment by mbutterick** [comment]
LGPL, because that's what most Racket libraries use. Apache is [not compatible with LGPL](http://www.apache.org/legal/resolved.html#category-x).
